files: \.(json|py|txt|yaml|yml)$
default_stages: [pre-commit, manual]
repos:

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
    - id: ruff
      args: [
      --fix,
      --unsafe-fixes,
      --target-version, "py314",
      --select, "ALL",
      --ignore, "CPY001,INP001,D,E501,T201,PLR0913"
      ]
    - id: ruff-format

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: pretty-format-json
      args: [
      --autofix,
      --indent, "4",
      --no-ensure-ascii,
      --no-sort-keys
      ]
    - id: requirements-txt-fixer
    - id: end-of-file-fixer
    - id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
    - id: mypy
      additional_dependencies: [types-requests]
      stages: [manual]
