name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '15/10 * 1-7,23-31 * *'
    - cron: '15 * 8-22 * *'

jobs:
  scheduled:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: "data"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Git Config
      run: |
        git config user.name woctezuma && git config user.email woctezuma@users.noreply.github.com

    - name: Run Updater
      run: |
        ./update.sh
      env:
        GOOGLE_BUCKET_NAME: ${{ secrets.GOOGLE_BUCKET_NAME }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
